from aiogram.dispatcher.filters.state import State, StatesGroup


class NormalCall(StatesGroup):
    # if no changes from user needed or no special cases occur
    # this is the only state group within bot will works,
    # thats why its 'NormalCall'
    waiting_for_pic = State()
    got_links_from_nao = State()
    getting_tags = State()
    reduce_tags = State()
    hashtags_generated = State()
    posting = State()

    class ForsedRedirect(StatesGroup):
        """states group where seach with yandex was started by error"""
        sub_pre_redirected = State()
        sub_geting_tags = State()
        sub_reduce_hashtags = State()
        sub_hashtags_generated = State()

    class UserInputEdit(StatesGroup):
        """states group for user edit caption to file manually"""
        pre_edit = State()
        waiting_for_input = State()
        tags_edited = State()

    class FilterApply(StatesGroup):
        """states group for editing caption with filters"""
        anal_filter_applyed = State()
        full_ignore_filters = State()
        partial_filter_applyed = State()

    class Error(StatesGroup):
        """state group for handling errors"""
        error_rised = State()
        carnaval_error_rised = State()

    class LikesConfirmation(StatesGroup):
        """states group to ignore capture generated by bot"""
        wait_for_likes_confirm = State()

    class EditMenu(StatesGroup):
        """states group to first route of changes maked by user"""
        in_menu = State()
        in_filters_menu = State()

        class ContinueEditing(StatesGroup):
            """states group for user to be able make more changes after first"""
            re_approve = State()
            in_menu = State()
            in_filters_menu = State()


states_to_press_no = [NormalCall.FilterApply.partial_filter_applyed,
                      NormalCall.FilterApply.anal_filter_applyed,
                      NormalCall.FilterApply.full_ignore_filters,
                      NormalCall.ForsedRedirect.sub_hashtags_generated,
                      NormalCall.UserInputEdit.tags_edited,
                      NormalCall.Error.carnaval_error_rised,
                      NormalCall.EditMenu.ContinueEditing.re_approve]
